# prefix
set -g prefix m-m

# colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:rgb:sync"

# base
set -s escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on

# bind-key
bind-key X kill-server
bind-key & kill-window
bind-key w kill-pane
bind-key d detach

# split
bind s split-window -v -c "#{pane_current_path}"
bind b split-window -h -c "#{pane_current_path}"
bind -n 'm-n' new-window -c "#{pane_current_path}"
bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'aserowy/tmux.nvim'
set -g @tmux-nvim-navigation false
set -g @tmux-nvim-resize false

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'select-pane -R'
bind-key -T copy-mode-vi 'm-h' select-pane -L
bind-key -T copy-mode-vi 'm-j' select-pane -D
bind-key -T copy-mode-vi 'm-k' select-pane -U
bind-key -T copy-mode-vi 'm-l' select-pane -R

# theme
set -g @plugin 'z3z1ma/tmux-gruvbox'
set -g @gruvbox_flavour 'dark'

set -g @gruvbox_window_status_enable "yes"
set -g @gruvbox_window_default_text "#W"
set -g @gruvbox_window_current_text "#W"

set -g @gruvbox_status_modules_right "date_time"
set -g @gruvbox_status_fill "icon"
set -g @gruvbox_date_time_text "%H:%M"

run '~/.config/tmux/plugins/tpm/tpm'
